### ISSUE TITLE
Error downloading GFS for sflux/

### ISSUE THREAD

**Issue by feiye-vims** [schism-dev/pyschism#138]
[2024-10-25 11:47:08,295] pyschism.forcing.nws.nws2.gfs2 INFO: file gfs.20181222/18/atmos/gfs.t18z.pgrb2.0p25.f006 is not available, try next file
[2024-10-25 11:47:08,295] pyschism.forcing.nws.nws2.gfs2 INFO: Downloading file gfs.20181222/12/atmos/gfs.t12z.pgrb2.0p25.f012 for 2018-12-23 00:00:00
[2024-10-25 11:47:08,315] pyschism.forcing.nws.nws2.gfs2 INFO: file gfs.20181222/12/atmos/gfs.t12z.pgrb2.0p25.f012 is not available, try next file
[2024-10-25 11:47:08,315] pyschism.forcing.nws.nws2.gfs2 INFO: Downloading file gfs.20181222/06/atmos/gfs.t06z.pgrb2.0p25.f018 for 2018-12-23 00:00:00
[2024-10-25 11:47:08,333] pyschism.forcing.nws.nws2.gfs2 INFO: No file for 2018-12-23 00:00:00
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/sciclone/home/yinglong/mambaforge/envs/pyschism/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/sciclone/home/yinglong/mambaforge/envs/pyschism/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/sciclone/home/yinglong/git/pyschism/pyschism/forcing/nws/nws2/gfs2.py", line 212, in gen_sflux
    lon, lat, idx_ymin, idx_ymax, idx_xmin, idx_xmax = self.modified_latlon(grbfiles[0])
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sciclone/schism10/yinglong/External_Exchanges/EX84/GFS/gen_sflux_gfs2.py", line 39, in <module>
    gfs.write(start_date=start, rnday=rnday, air=True, prc=True, rad=True)
  File "/sciclone/home/yinglong/git/pyschism/pyschism/forcing/nws/nws2/gfs2.py", line 177, in write
    pool.starmap(self.gen_sflux, [(istack+1, date, air, prc, rad) for istack, date in enumerate(datevector)])
  File "/sciclone/home/yinglong/mambaforge/envs/pyschism/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/sciclone/home/yinglong/mambaforge/envs/pyschism/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
IndexError: list index out of range
/sciclone/home/yinglong/DISKS/schism10/External_Exchanges/EX84/GFS% vi gen_sflux_gfs2.py

**Comment by pierrechabert** [comment]
It seems that this issue is still occurring when generating sflux with GFS. Is there any hints on how to get around this problem?
