### ISSUE TITLE
Needs to check download time period for GFS

### ISSUE THREAD

**Issue by feiye-vims** [schism-dev/pyschism#140]
pyschism/pyschism/forcing/nws/nws2/gfs2.py

Need to check if the requested download time period is available in the AWS data registry https://aws.amazon.com/marketplace/pp/prodview-hok7o2o24ktfi#resources 

The current error message is not clear enough:

Traceback (most recent call last):
  File "/sciclone/home/feiye/mambaforge/envs/stofs/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/sciclone/home/feiye/mambaforge/envs/stofs/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/sciclone/data10/feiye/pyschism/pyschism/forcing/nws/nws2/gfs2.py", line 212, in gen_sflux
    lon, lat, idx_ymin, idx_ymax, idx_xmin, idx_xmax = self.modified_latlon(grbfiles[0])
IndexError: list index out of range

**Comment by feiye-vims** [comment]
Done.

git hash: 00b1137
