### ISSUE TITLE
pyproj > 2.6 won't work

### ISSUE THREAD

**Issue by cuill** [schism-dev/pyschism#24]
I received this error with pyproj==3.1.0

Traceback (most recent call last):
  File "test_geoviews.py", line 50, in <module>
    elev=Hgrid.open('maxelev.gr3',crs='EPSG:4326')
  File "/anaconda3/envs/post_processing/lib/python3.8/site-packages/pyschism/mesh/hgrid.py", line 144, in open
    return Hgrid(**_grd)
  File "/anaconda3/envs/post_processing/lib/python3.8/site-packages/pyschism/mesh/hgrid.py", line 134, in __init__
    super().__init__(*args, **kwargs)
  File "/anaconda3/envs/post_processing/lib/python3.8/site-packages/pyschism/mesh/base.py", line 415, in __init__
    self.nodes = Nodes(nodes, crs)
  File "/anaconda3/envs/post_processing/lib/python3.8/site-packages/pyschism/mesh/base.py", line 56, in __init__
    self._crs = CRS.from_user_input(crs) if crs is not None else crs
  File "/anaconda3/envs/post_processing/lib/python3.8/site-packages/pyproj/crs/crs.py", line 440, in from_user_input
    return CRS(value, **kwargs)
  File "/anaconda3/envs/post_processing/lib/python3.8/site-packages/pyproj/crs/crs.py", line 296, in __init__
    super().__init__(projstring)
  File "pyproj/_crs.pyx", line 2338, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: EPSG:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name)

**Comment by jreniel** [comment]
Thanks for reporting this. There's a note [about this](https://pyproj4.github.io/pyproj/stable/gotchas.html#internal-proj-error-sqlite-error-on-select) on the pyproj website. Could you take a look at it to see if it resolves the issue?

**Comment by jreniel** [comment]
And there's also this [issue](https://github.com/geopandas/geopandas/issues/1887#issue-838836559).

**Comment by jreniel** [comment]
@cuill  During our tests yesterday this issue didn't seem to come up, so I will assume this was an outdated dependency issue that gets resolved simply by updating Pyproj. Feel free to reopen is the issue arises again.
